version: '1'

services:
  jwtapiapp:
    image: jwtapi
    container_name: jwtapiapp
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080
    ports:
      - 8080:8080
    networks:
      - mybridgenetwork
    restart: always

  postgres:
    image: postgres
    container_name: postgresdb
    environment:
      - POSTGRES_USER=emil
      - POSTGRES_PASSWORD=Secret123!
      - POSTGRES_DB=library
    networks:
      - mybridgenetwork
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - mypostgresvolume:/data/db
      - mypostgresvolume:/data/configdb
    restart: always



networks:
  mybridgenetwork:
    driver: bridge
  
volumes:
  mypostgresvolume: